package com.everyones_coupon.integration;

import com.everyones_coupon.repository.AdminTokenRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@TestPropertySource(properties = {"app.admin.auto-generate:true"})
public class AdminTokenInitializerIntegrationTest {

    @Autowired
    private AdminTokenRepository adminTokenRepository;

    @Test
    void adminTokenAutoGeneratedAndStored() {
        assertThat(adminTokenRepository.count()).isGreaterThan(0);
    }
}
